version: "3"

services:
  common:
    build: ./common
    volumes:
      - ./common:/app/common
      - /app/common/node_modules

  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app/client
      - ./common:/app/common
      - /app/client/node_modules
      - /app/common/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - common
      - server

  server:
    build: ./server
    ports:
      - "5001:5001"
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mydb
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - common
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
